<a href="https://colab.research.google.com/github/muditkumar14/aiml/blob/main/Mudit_Kumar_Singh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}


In [2]:
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}


In [3]:
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}


TASK 1


In [4]:
import numpy as np
import pandas as pd

Students= pd.DataFrame(students_data)
Enrollments=pd.DataFrame(enrollments_data)
Scores=pd.DataFrame(scores_data)

In [5]:
Students

,student_id,name,email,city
0,101,Alice,alice@email.com,Mumbai
1,102,Bob,bob@email.com,Delhi
2,103,None,charlie@email.com,Bangalore
3,104,David,None,Mumbai
4,105,Emma,emma@email.com,None
5,106,Frank,frank@email.com,Chennai
6,107,Grace,grace@email.com,Delhi


In [6]:
Enrollments

,student_id,course_name,enrollment_date
0,101,Python,2024-01-15
1,102,Data Science,2024-01-20
2,103,Python,2024-02-01
3,105,Machine Learning,2024-02-10
4,108,AI,2024-02-15
5,109,Python,2024-03-01


In [7]:
Scores

,student_id,exam_score
0,101,85
1,102,92
2,104,78
3,105,88
4,106,95


In [8]:
print("=== NULL VALUE ANALYSIS ===")
null_counts = Students.isnull().sum()
null_percentages = (null_counts / len(Students)) * 100

for column in Students.columns:
    print(f"Column: {column}, Nulls: {null_counts[column]} ({null_percentages[column]:.2f}%)")

=== NULL VALUE ANALYSIS ===
Column: student_id, Nulls: 0 (0.00%)
Column: name, Nulls: 1 (14.29%)
Column: email, Nulls: 1 (14.29%)
Column: city, Nulls: 1 (14.29%)


In [9]:
Students['city']=Students['city'].fillna('Unknown')

In [10]:
Students=Students.dropna(subset='name')

In [11]:
Students

,student_id,name,email,city
0,101,Alice,alice@email.com,Mumbai
1,102,Bob,bob@email.com,Delhi
3,104,David,None,Mumbai
4,105,Emma,emma@email.com,Unknown
5,106,Frank,frank@email.com,Chennai
6,107,Grace,grace@email.com,Delhi


TASK 2

In [12]:
pd.merge(Students,Enrollments,on='student_id',how='inner')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10


Q.How many students appear in the result?
A.3

Q.Which students from the students table are excluded and why?
A.3 as we have done innerjoin and 103 is drop as name is NONE and 104,106 and 107 as not matched.

In [13]:
pd.merge(Students,Enrollments,on='student_id',how='left')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,104,David,None,Mumbai,NaN,NaN
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,106,Frank,frank@email.com,Chennai,NaN,NaN
5,107,Grace,grace@email.com,Delhi,NaN,NaN


Q.How many total rows are in the result?
A. 6

Q.Which students have null values in course_name and why?
A.3 as when we do left join all the left data is selected and doen't matter if the matched data is on right side.[104, 106, 107]

In [14]:
pd.merge(Students,Enrollments,on='student_id',how='right')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
4,108,NaN,NaN,NaN,AI,2024-02-15
5,109,NaN,NaN,NaN,Python,2024-03-01


Q.How many total rows are in the result?
A.6

Q.Which student_ids appear in the result but don't have student names?
A. 103,108,109

In [15]:
pd.merge(Students,Enrollments,on='student_id',how='outer')

,student_id,name,email,city,course_name,enrollment_date
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20
2,103,NaN,NaN,NaN,Python,2024-02-01
3,104,David,None,Mumbai,NaN,NaN
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10
5,106,Frank,frank@email.com,Chennai,NaN,NaN
6,107,Grace,grace@email.com,Delhi,NaN,NaN
7,108,NaN,NaN,NaN,AI,2024-02-15
8,109,NaN,NaN,NaN,Python,2024-03-01


Q.How many total rows are in the result?
A.9

Q.Display rows where either student name is null OR course_name is null
A.rowno. 3,4,6,7,8,9

In [16]:
pd.merge(Students,Enrollments,on='student_id',how='outer',indicator=True)

,student_id,name,email,city,course_name,enrollment_date,_merge
0,101,Alice,alice@email.com,Mumbai,Python,2024-01-15,both
1,102,Bob,bob@email.com,Delhi,Data Science,2024-01-20,both
2,103,NaN,NaN,NaN,Python,2024-02-01,right_only
3,104,David,None,Mumbai,NaN,NaN,left_only
4,105,Emma,emma@email.com,Unknown,Machine Learning,2024-02-10,both
5,106,Frank,frank@email.com,Chennai,NaN,NaN,left_only
6,107,Grace,grace@email.com,Delhi,NaN,NaN,left_only
7,108,NaN,NaN,NaN,AI,2024-02-15,right_only
8,109,NaN,NaN,NaN,Python,2024-03-01,right_only


Task 3 Lookup Operation and Automation

In [17]:
score_lookup=dict(zip(students_data['student_id'],scores_data['exam_score']))
print(score_lookup)

{101: 85, 102: 92, 103: 78, 104: 88, 105: 95}


In [26]:
Students['exam_score'] = Students['student_id'].map(score_lookup).fillna('No Score')
Students

/tmp/ipykernel_613/3647521711.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Students['exam_score'] = Students['student_id'].map(score_lookup).fillna('No Score')


,student_id,name,email,city,exam_score
0,101,Alice,alice@email.com,Mumbai,85.0
1,102,Bob,bob@email.com,Delhi,92.0
3,104,David,None,Mumbai,88.0
4,105,Emma,emma@email.com,Unknown,95.0
5,106,Frank,frank@email.com,Chennai,No Score
6,107,Grace,grace@email.com,Delhi,No Score


In [30]:
pd.merge(Students,Scores,on='student_id',how='left')

,student_id,name,email,city,exam_score_x,exam_score_y
0,101,Alice,alice@email.com,Mumbai,85.0,85.0
1,102,Bob,bob@email.com,Delhi,92.0,92.0
2,104,David,None,Mumbai,88.0,88.0
3,105,Emma,emma@email.com,Unknown,95.0,95.0
4,106,Frank,frank@email.com,Chennai,No Score,No Score
5,107,Grace,grace@email.com,Delhi,No Score,NaN


map perform fast as per the element wise. on the other hand merge uses more complex operation like joing Dataframes

In [31]:
def auto_merge(left, right, key, join_type="left"):
    """
    Merges two DataFrames and reports row changes.
    join_type: 'inner', 'left', 'right', or 'outer'
    """
    result = pd.merge(left, right, on=key, how=join_type)

    print(f"=== MERGE REPORT ({join_type.upper()} JOIN on '{key}') ===")
    print(f"  Left table rows:   {len(left)}")
    print(f"  Right table rows:  {len(right)}")
    print(f"  Result rows:       {len(result)}")

    nulls = result.isnull().sum().sum()
    if nulls > 0:
        print(f"  NaN values added:  {nulls} (unmatched rows)")
    else:
        print(f"  NaN values added:  0 (all rows matched)")
    print()
    return result

In [47]:
def auto_merge(df1, df2, join_type, key_column):

    print("Automation Function Test:")
    merged_df = pd.merge(df1, df2, how=join_type, on=key_column)
    row_count = merged_df.shape[0]

    result_dict = {
        'result_df': merged_df,
        'row_count': row_count,
        'join_type': join_type
    }
    return result_dict

In [48]:
result=auto_merge(Students,Enrollments,'left','student_id')
result


Automation Function Test:


{'result_df':    student_id   name            email     city exam_score       course_name  \
 0         101  Alice  alice@email.com   Mumbai       85.0            Python   
 1         102    Bob    bob@email.com    Delhi       92.0      Data Science   
 2         104  David             None   Mumbai       88.0               NaN   
 3         105   Emma   emma@email.com  Unknown       95.0  Machine Learning   
 4         106  Frank  frank@email.com  Chennai   No Score               NaN   
 5         107  Grace  grace@email.com    Delhi   No Score               NaN   
 
   enrollment_date  
 0      2024-01-15  
 1      2024-01-20  
 2             NaN  
 3      2024-02-10  
 4             NaN  
 5             NaN  ,
 'row_count': 6,
 'join_type': 'left'}

In [49]:
result=auto_merge(Students,Enrollments,'inner','student_id')
result


Automation Function Test:


{'result_df':    student_id   name            email     city exam_score       course_name  \
 0         101  Alice  alice@email.com   Mumbai       85.0            Python   
 1         102    Bob    bob@email.com    Delhi       92.0      Data Science   
 2         105   Emma   emma@email.com  Unknown       95.0  Machine Learning   
 
   enrollment_date  
 0      2024-01-15  
 1      2024-01-20  
 2      2024-02-10  ,
 'row_count': 3,
 'join_type': 'inner'}